require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MensajesController do

  # This should return the minimal set of attributes required to create a valid
  # Mensaje. As you add validations to Mensaje, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mensajes as @mensajes" do
      mensaje = Mensaje.create! valid_attributes
      get :index
      assigns(:mensajes).should eq([mensaje])
    end
  end

  describe "GET show" do
    it "assigns the requested mensaje as @mensaje" do
      mensaje = Mensaje.create! valid_attributes
      get :show, :id => mensaje.id.to_s
      assigns(:mensaje).should eq(mensaje)
    end
  end

  describe "GET new" do
    it "assigns a new mensaje as @mensaje" do
      get :new
      assigns(:mensaje).should be_a_new(Mensaje)
    end
  end

  describe "GET edit" do
    it "assigns the requested mensaje as @mensaje" do
      mensaje = Mensaje.create! valid_attributes
      get :edit, :id => mensaje.id.to_s
      assigns(:mensaje).should eq(mensaje)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mensaje" do
        expect {
          post :create, :mensaje => valid_attributes
        }.to change(Mensaje, :count).by(1)
      end

      it "assigns a newly created mensaje as @mensaje" do
        post :create, :mensaje => valid_attributes
        assigns(:mensaje).should be_a(Mensaje)
        assigns(:mensaje).should be_persisted
      end

      it "redirects to the created mensaje" do
        post :create, :mensaje => valid_attributes
        response.should redirect_to(Mensaje.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mensaje as @mensaje" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mensaje.any_instance.stub(:save).and_return(false)
        post :create, :mensaje => {}
        assigns(:mensaje).should be_a_new(Mensaje)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mensaje.any_instance.stub(:save).and_return(false)
        post :create, :mensaje => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mensaje" do
        mensaje = Mensaje.create! valid_attributes
        # Assuming there are no other mensajes in the database, this
        # specifies that the Mensaje created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mensaje.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mensaje.id, :mensaje => {'these' => 'params'}
      end

      it "assigns the requested mensaje as @mensaje" do
        mensaje = Mensaje.create! valid_attributes
        put :update, :id => mensaje.id, :mensaje => valid_attributes
        assigns(:mensaje).should eq(mensaje)
      end

      it "redirects to the mensaje" do
        mensaje = Mensaje.create! valid_attributes
        put :update, :id => mensaje.id, :mensaje => valid_attributes
        response.should redirect_to(mensaje)
      end
    end

    describe "with invalid params" do
      it "assigns the mensaje as @mensaje" do
        mensaje = Mensaje.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mensaje.any_instance.stub(:save).and_return(false)
        put :update, :id => mensaje.id.to_s, :mensaje => {}
        assigns(:mensaje).should eq(mensaje)
      end

      it "re-renders the 'edit' template" do
        mensaje = Mensaje.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mensaje.any_instance.stub(:save).and_return(false)
        put :update, :id => mensaje.id.to_s, :mensaje => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mensaje" do
      mensaje = Mensaje.create! valid_attributes
      expect {
        delete :destroy, :id => mensaje.id.to_s
      }.to change(Mensaje, :count).by(-1)
    end

    it "redirects to the mensajes list" do
      mensaje = Mensaje.create! valid_attributes
      delete :destroy, :id => mensaje.id.to_s
      response.should redirect_to(mensajes_url)
    end
  end

end
