require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NoticiaController do

  def mock_noticium(stubs={})
    @mock_noticium ||= mock_model(Noticium, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all noticia as @noticia" do
      Noticium.stub(:all) { [mock_noticium] }
      get :index
      assigns(:noticia).should eq([mock_noticium])
    end
  end

  describe "GET show" do
    it "assigns the requested noticium as @noticium" do
      Noticium.stub(:find).with("37") { mock_noticium }
      get :show, :id => "37"
      assigns(:noticium).should be(mock_noticium)
    end
  end

  describe "GET new" do
    it "assigns a new noticium as @noticium" do
      Noticium.stub(:new) { mock_noticium }
      get :new
      assigns(:noticium).should be(mock_noticium)
    end
  end

  describe "GET edit" do
    it "assigns the requested noticium as @noticium" do
      Noticium.stub(:find).with("37") { mock_noticium }
      get :edit, :id => "37"
      assigns(:noticium).should be(mock_noticium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created noticium as @noticium" do
        Noticium.stub(:new).with({'these' => 'params'}) { mock_noticium(:save => true) }
        post :create, :noticium => {'these' => 'params'}
        assigns(:noticium).should be(mock_noticium)
      end

      it "redirects to the created noticium" do
        Noticium.stub(:new) { mock_noticium(:save => true) }
        post :create, :noticium => {}
        response.should redirect_to(noticium_url(mock_noticium))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved noticium as @noticium" do
        Noticium.stub(:new).with({'these' => 'params'}) { mock_noticium(:save => false) }
        post :create, :noticium => {'these' => 'params'}
        assigns(:noticium).should be(mock_noticium)
      end

      it "re-renders the 'new' template" do
        Noticium.stub(:new) { mock_noticium(:save => false) }
        post :create, :noticium => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested noticium" do
        Noticium.stub(:find).with("37") { mock_noticium }
        mock_noticium.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :noticium => {'these' => 'params'}
      end

      it "assigns the requested noticium as @noticium" do
        Noticium.stub(:find) { mock_noticium(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:noticium).should be(mock_noticium)
      end

      it "redirects to the noticium" do
        Noticium.stub(:find) { mock_noticium(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(noticium_url(mock_noticium))
      end
    end

    describe "with invalid params" do
      it "assigns the noticium as @noticium" do
        Noticium.stub(:find) { mock_noticium(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:noticium).should be(mock_noticium)
      end

      it "re-renders the 'edit' template" do
        Noticium.stub(:find) { mock_noticium(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested noticium" do
      Noticium.stub(:find).with("37") { mock_noticium }
      mock_noticium.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the noticia list" do
      Noticium.stub(:find) { mock_noticium }
      delete :destroy, :id => "1"
      response.should redirect_to(noticia_url)
    end
  end

end
