require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PorrasController do

  # This should return the minimal set of attributes required to create a valid
  # Porra. As you add validations to Porra, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all porras as @porras" do
      porra = Porra.create! valid_attributes
      get :index
      assigns(:porras).should eq([porra])
    end
  end

  describe "GET show" do
    it "assigns the requested porra as @porra" do
      porra = Porra.create! valid_attributes
      get :show, :id => porra.id.to_s
      assigns(:porra).should eq(porra)
    end
  end

  describe "GET new" do
    it "assigns a new porra as @porra" do
      get :new
      assigns(:porra).should be_a_new(Porra)
    end
  end

  describe "GET edit" do
    it "assigns the requested porra as @porra" do
      porra = Porra.create! valid_attributes
      get :edit, :id => porra.id.to_s
      assigns(:porra).should eq(porra)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Porra" do
        expect {
          post :create, :porra => valid_attributes
        }.to change(Porra, :count).by(1)
      end

      it "assigns a newly created porra as @porra" do
        post :create, :porra => valid_attributes
        assigns(:porra).should be_a(Porra)
        assigns(:porra).should be_persisted
      end

      it "redirects to the created porra" do
        post :create, :porra => valid_attributes
        response.should redirect_to(Porra.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved porra as @porra" do
        # Trigger the behavior that occurs when invalid params are submitted
        Porra.any_instance.stub(:save).and_return(false)
        post :create, :porra => {}
        assigns(:porra).should be_a_new(Porra)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Porra.any_instance.stub(:save).and_return(false)
        post :create, :porra => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested porra" do
        porra = Porra.create! valid_attributes
        # Assuming there are no other porras in the database, this
        # specifies that the Porra created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Porra.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => porra.id, :porra => {'these' => 'params'}
      end

      it "assigns the requested porra as @porra" do
        porra = Porra.create! valid_attributes
        put :update, :id => porra.id, :porra => valid_attributes
        assigns(:porra).should eq(porra)
      end

      it "redirects to the porra" do
        porra = Porra.create! valid_attributes
        put :update, :id => porra.id, :porra => valid_attributes
        response.should redirect_to(porra)
      end
    end

    describe "with invalid params" do
      it "assigns the porra as @porra" do
        porra = Porra.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Porra.any_instance.stub(:save).and_return(false)
        put :update, :id => porra.id.to_s, :porra => {}
        assigns(:porra).should eq(porra)
      end

      it "re-renders the 'edit' template" do
        porra = Porra.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Porra.any_instance.stub(:save).and_return(false)
        put :update, :id => porra.id.to_s, :porra => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested porra" do
      porra = Porra.create! valid_attributes
      expect {
        delete :destroy, :id => porra.id.to_s
      }.to change(Porra, :count).by(-1)
    end

    it "redirects to the porras list" do
      porra = Porra.create! valid_attributes
      delete :destroy, :id => porra.id.to_s
      response.should redirect_to(porras_url)
    end
  end

end
